appbuild_user_login:
    path:     /login
    defaults: { _controller: AppBuildUserBundle:Security:login }

appbuild_user_register:
    path:   /register
    defaults: { _controller: AppBuildUserBundle:Security:register }

appbuild_user_edit:
    path:   /account
    defaults: { _controller: AppBuildUserBundle:Security:editUser }
