
appbuild_admin_build:
    resource: '@AppbuildApplicationBundle/Resources/config/routing/admin/build.yml'
    prefix: '/application/{application_id}/build'

appbuild_admin_application:
    resource: '@AppbuildApplicationBundle/Resources/config/routing/admin/application.yml'
    prefix: '/application'
