
# Applications
appbuild_api_application_list:
    path:     '/'
    defaults: { _controller: 'AppbuildApplicationBundle:Api/Application:list' }
    methods:  [GET, HEAD]

appbuild_api_application_get:
    path:     '/{id}'
    defaults: { _controller: 'AppbuildApplicationBundle:Api/Application:get' }
    methods:  [GET, HEAD]
