
# Application Builds
appbuild_api_application_build_add:
    path:     '/'
    defaults: { _controller: 'AppbuildApplicationBundle:Api/Build:createForApplication' }
    methods:  [PUT]

appbuild_api_application_build_list:
    path:     '/'
    defaults: { _controller: 'AppbuildApplicationBundle:Api/Build:listForApplication' }
    methods:  [GET, HEAD]

appbuild_api_application_build_get_latest:
    path:     '/latest'
    defaults: { _controller: 'AppbuildApplicationBundle:Api/Build:getLatestForApplication' }
    methods:  [GET, HEAD]
