
# Builds
appbuild_api_build_get:
    path:     '/{id}'
    defaults: { _controller: 'AppbuildApplicationBundle:Api/Build:get' }
    methods:  [GET, HEAD]

appbuild_api_build_add_file:
    path:     '/{id}/file'
    defaults: { _controller: 'AppbuildApplicationBundle:Api/Build:uploadFile' }
    methods:  [PUT]
