
appbuild_api_application_build:
    resource: '@AppbuildApplicationBundle/Resources/config/routing/api/application_build.yml'
    prefix: '/application/{application_id}/build'

appbuild_api_application:
    resource: '@AppbuildApplicationBundle/Resources/config/routing/api/application.yml'
    prefix: '/application'

appbuild_api_build:
    resource: '@AppbuildApplicationBundle/Resources/config/routing/api/build.yml'
    prefix: '/build'
