language: php

php:
  - 5.6

before_script:
  - npm install -g bower
  - gem install sass
  - make test-prepare

script:
  - bin/phpunit -c app --testsuite appbuild_project --coverage-clover=coverage.clover
  - bin/behat --profile default --no-interaction
