language: php

php:
  - 5.6
  - 7.0

before_script:
  - nvm install "$(jq -r '.engines.node' package.json)"
  - make test-prepare

script:
  - bin/phpunit --testsuite="majoraotastore_project" --coverage-clover="coverage.clover"
  - bin/behat --no-interaction
  - bin/behat --no-interaction --profile="nostream"
