
# Misc routing
appbuild_misc:
    resource: 'routing/routing_misc.yml'

# API routing
appbuild_api:
    resource: 'routing/routing_api.yml'
    prefix: '/api'

# Admin routing
appbuild_admin:
    resource: 'routing/routing_admin.yml'
    prefix: '/{_locale}'
    defaults:
        _locale: '%default_locale%'
    requirements:
        _locale: '%routing_locales%'
    options:
        expose: true

# /
appbuild_main:
    path:  '/'
    defaults:
        _controller: 'FrameworkBundle:Redirect:redirect'
        route: 'appbuild_main_locale'
        permanent: true

# /locale
appbuild_main_locale:
    path: '/%default_locale%'
    defaults:
        _controller: 'FrameworkBundle:Redirect:redirect'
        route: 'appbuild_admin_application_list'
        permanent: true

# Login_check
appbuild_user_login_check:
    path: '/login_check'

# Logout
appbuild_user_logout:
    path: '/logout'
