
# Appbuild misc routing
majoraotastore_misc:
    resource: 'routing/routing_misc.yml'
    prefix: '/_misc'

# Appbuild admin routing
majoraotastore_admin:
    resource: 'routing/routing_admin.yml'
    prefix: '/{_locale}/'
    defaults:
        _locale: '%default_locale%'
    requirements:
        _locale: '%routing_locales%'
    options:
        expose: true

# Redirect majoraotastore_main route to majoraotastore_main_locale route
majoraotastore_main:
    path:  /
    defaults:
        _controller: 'FrameworkBundle:Redirect:redirect'
        route: 'majoraotastore_main_locale'
        permanent: true

# Redirect majoraotastore_main_locale to majoraotastore_user_login route
majoraotastore_main_locale:
    path: '/%default_locale%'
    defaults:
        _controller: 'FrameworkBundle:Redirect:redirect'
        route: 'majoraotastore_admin_application_list'
        permanent: true

# Login_check
majoraotastore_user_login_check:
    path: '/login_check'
# Logout
majoraotastore_user_logout:
    path: '/logout'
