
# Misc routing
majoraotastore_misc:
    resource: 'routing/routing_misc.yml'
    prefix: '/_misc'

# API routing
majoraotastore_api:
    resource: 'routing/routing_api.yml'
    prefix: '/api'

# Admin routing
majoraotastore_admin:
    resource: 'routing/routing_admin.yml'
    prefix: '/{_locale}'
    defaults:
        _locale: '%default_locale%'
    requirements:
        _locale: '%routing_locales%'
    options:
        expose: true

# /
majoraotastore_main:
    path:  '/'
    defaults:
        _controller: 'FrameworkBundle:Redirect:redirect'
        route: 'majoraotastore_main_locale'
        permanent: true

# /locale
majoraotastore_main_locale:
    path: '/%default_locale%'
    defaults:
        _controller: 'FrameworkBundle:Redirect:redirect'
        route: 'majoraotastore_admin_application_list'
        permanent: true

# Login_check
majoraotastore_user_login_check:
    path: '/login_check'

# Logout
majoraotastore_user_logout:
    path: '/logout'
