security:
    encoders:
        AppBuild\Bundle\UserBundle\Entity\User:
           algorithm: bcrypt    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    providers:
        db_user_provider:
           entity:
               class: AppBuildUserBundle:User
               property: email

    firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: appbuild_user_login
                check_path: /login_check
                default_target_path: appbuild_admin_application_list
                always_use_default_target_path: true
            logout:
                path: appbuild_user_logout
                target: appbuild_user_login
            provider: db_user_provider

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER]

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_SUPER_ADMIN }
