user_name: vagrant
projects_dir: /var/www/
ssh_key: ~/.ssh/id_rsa

pools:
  - { name: 'www', user: 'vagrant', group: 'vagrant', listen: '127.0.0.1:9000' }

php_memory_limit: 2G

sites:
  - { name: 'appbuild', docroot: '/var/www/AppBuildServer/web', server_name: '*.app-build.dev' }

mysql:
  databases:
    - { name: 'appbuild' }

  users:
    - { name: 'appbuild', host: '%' }

  bind_address: 0.0.0.0
