
# Users
appbuild_user_list:
    path:     /
    defaults: { _controller: AppBuildUserBundle:Security:list }

appbuild_user_create:
    path:     /create
    defaults: { _controller: AppBuildUserBundle:Security:create }

appbuild_user_update:
    path:     /{id}/update
    defaults: { _controller: AppBuildUserBundle:Security:update }

appbuild_user_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBuildUserBundle:Security:delete }

appbuild_user_toggle_enable:
    path:     /{id}/enable
    defaults: { _controller: AppBuildUserBundle:Security:toggleEnable }
