AppBuild\Bundle\ApplicationBundle\Entity\Application:
    type: entity
    repositoryClass: 'AppBuild\Bundle\ApplicationBundle\Entity\ApplicationRepository'
    table: appbuild_application
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    uniqueConstraints:
        label_idx:
            columns: label
        slug_idx:
            columns: slug
    fields:
        label:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                    separator: -
                    style: default
                    fields:
                        - label
        support:
            type: string
        enabled:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        builds:
            targetEntity: 'AppBuild\Bundle\ApplicationBundle\Entity\Build'
            mappedBy: application
            cascade: ['persist', 'remove']
    manyToMany:
        users:
            targetEntity: 'AppBuild\Bundle\UserBundle\Entity\User'
            inversedBy: applications
            cascade: ['persist']
            joinTable:
                name: appbuild_application_user
                joinColumns:
                    application_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
