AppBuild\Bundle\ApplicationBundle\Entity\Build:
    type: entity
    repositoryClass: AppBuild\Bundle\ApplicationBundle\Entity\BuildRepository
    table: appbuild_build
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        version:
            type: string
        filePath:
            type: string
            column: file_path
        enabled:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        application:
            targetEntity: AppBuild\Bundle\ApplicationBundle\Entity\Application
            inversedBy: builds
            joinColumn:
                name: application_id
                referencedColumnName: id
                onDelete: cascade
