LinkValue\Appbuild\ApplicationBundle\Entity\BuildToken:
    type: entity
    repositoryClass: 'LinkValue\Appbuild\ApplicationBundle\Entity\BuildTokenRepository'
    table: appbuild_build_token
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        token:
            type: string
        expiredAt:
            type: datetime
            column: expired_at
    manyToOne:
        build:
            targetEntity: 'LinkValue\Appbuild\ApplicationBundle\Entity\Build'
            inversedBy: buildTokens
            joinColumn:
                name: build_id
                referencedColumnName: id
                onDelete: cascade
