majoraotastore_user_login:
    path:     /login
    defaults: { _controller: MajoraOTAStoreUserBundle:Security:login }

majoraotastore_user_my_account:
    path:     /account
    defaults: { _controller: MajoraOTAStoreUserBundle:Security:myAccount }

majoraotastore_user:
    resource: "@MajoraOTAStoreUserBundle/Resources/config/routing/user.yml"
    prefix: /user
