appbuild_admin_user_login:
    path: '/login'
    defaults: { _controller: 'AppbuildUserBundle:Security:login' }

appbuild_admin_user_my_account:
    path: '/account'
    defaults: { _controller: 'AppbuildUserBundle:Security:myAccount' }

appbuild_admin_user:
    resource: '@AppbuildUserBundle/Resources/config/routing/admin/user.yml'
    prefix: '/user'
