
# Users
appbuild_admin_user_list:
    path:     /
    defaults: { _controller: AppbuildUserBundle:Security:list }

appbuild_admin_user_create:
    path:     /create
    defaults: { _controller: AppbuildUserBundle:Security:create }

appbuild_admin_user_update:
    path:     /{id}/update
    defaults: { _controller: AppbuildUserBundle:Security:update }

appbuild_admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: AppbuildUserBundle:Security:delete }

appbuild_admin_user_toggle_enable:
    path:     /{id}/enable
    defaults: { _controller: AppbuildUserBundle:Security:toggleEnable }
