app_upload:
    path:     /upload
    defaults: { _controller: AppBundle:AppBuild:create }

app_update:
    path:     /update/{id}
    defaults: { _controller: AppBundle:AppBuild:update }

app_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:AppBuild:delete }

app_download:
    path:     /download/{id}
    defaults: { _controller: AppBundle:AppBuild:download }

app_get_manifest:
    path:    /manifest/{id}
    defaults: { _controller: AppBundle:AppBuild:getManifest }
