LinkValue\Appbuild\ApplicationBundle\Entity\Application:
    constraints:
        - Callback: validatePackageName
        - Callback: validateDisplayImage
        - Callback: validateFullSizeImage
    properties:
        support:
            - Choice:
                callback: getAvailableSupports
