AppBundle\Entity\Application:
    type: entity
    repositoryClass: AppBundle\Entity\ApplicationRepository
    table: application
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        slug:
          type: string
          gedmo:
            slug:
              separator: _
              style: camel
              fields:
                - name
        version:
            type: string
            nullable: true
        filePath:
            type: string
            column: file_path
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
