#########################################################
#                                                       #
# Ansible Galaxy requirements file for non-Majora roles #
#                                                       #
# Theses roles will be installed in "roles" folder.     #
#                                                       #
#########################################################

- name: ruby
  src: https://github.com/rvm/rvm1-ansible
  version: v1.3.8
