# Appbuild admin routing
majoraotastore_admin_applicationbundle:
    resource: "@MajoraOTAStoreApplicationBundle/Resources/config/routing.yml"
    prefix:   /
majoraotastore_userbundle:
    resource: "@MajoraOTAStoreUserBundle/Resources/config/routing.yml"
    prefix:   /
