# API routing
appbuild_api_login_check:
    path: '/login_check'

appbuild_api_applicationbundle:
    resource: '@AppbuildApplicationBundle/Resources/config/routing/api/routing.yml'
    prefix:   '/'
