# Appbuild admin routing
appbuild_admin_applicationbundle:
    resource: "@AppBuildApplicationBundle/Resources/config/routing.yml"
    prefix:   /
appbuild_user:
    resource: "@AppBuildUserBundle/Resources/config/routing.yml"
    prefix:   /
