# Admin routing
majoraotastore_admin_applicationbundle:
    resource: '@MajoraOTAStoreApplicationBundle/Resources/config/routing/admin/routing.yml'
    prefix:   '/'
majoraotastore_admin_userbundle:
    resource: '@MajoraOTAStoreUserBundle/Resources/config/routing/admin/routing.yml'
    prefix:   '/'
