# Admin routing
appbuild_admin_applicationbundle:
    resource: '@AppbuildApplicationBundle/Resources/config/routing/admin/routing.yml'
    prefix:   '/'
appbuild_admin_userbundle:
    resource: '@AppbuildUserBundle/Resources/config/routing/admin/routing.yml'
    prefix:   '/'
